[package]
name = "snarkvm-console-algorithms"
version = "0.7.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Console algorithms for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[dependencies.snarkvm-curves]
path = "../../curves"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-fields]
path = "../../fields"
version = "0.7.5"
default-features = false

[dependencies.snarkvm-utilities]
path = "../../utilities"
version = "0.7.5"

[dependencies.anyhow]
version = "1.0.58"

[dependencies.blake2s_simd]
version = "1.0"

[dependencies.itertools]
version = "0.10.1"

[dependencies.smallvec]
version = "1.8"
default-features = false
features = [ "const_generics", "const_new" ]

[dev-dependencies.expect-test]
version = "1.2"

[dev-dependencies.hex]
version = "0.4"

[dev-dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies.serde_json]
version = "1.0"
